---
- name: Deploy Applications
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull MySQL Docker Image
      docker_image:
        name: mysql
        tag: latest
        source: pull

    - name: Pull Backend Docker Image
      docker_image:
        name: tnehara831/air-line-ticket-booking-img-backend
        tag: latest
        source: pull

    - name: Pull Frontend Docker Image
      docker_image:
        name: tnehara831/air-line-ticket-booking-img
        tag: latest
        source: pull

    - name: Run MySQL Container
      docker_container:
        name: mysql_container
        image: mysql:latest
        state: started
        restart_policy: always
        ports:
          - "3307:3306"
        env:
          MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
          MYSQL_DATABASE: "{{ mysql_database }}"
          MYSQL_USER: "{{ mysql_user }}"
          MYSQL_PASSWORD: "{{ mysql_password }}"

    - name: Run Backend Container
      docker_container:
        name: backend_app
        image: tnehara831/air-line-ticket-booking-backend:latest
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
        env:
          DB_HOST: "mysql_container"
          DB_USER: "{{ mysql_user }}"
          DB_PASS: "{{ mysql_password }}"
          DB_NAME: "{{ mysql_database }}"

    - name: Run Frontend Container
      docker_container:
        name: frontend_app
        image: tnehara831/air-line-ticket-booking-frontend:latest
        state: started
        restart_policy: always
        ports:
          - "3000:80"
